.PHONY: clean All

All:
	@echo "----------Building project:[ Bp3_proje1 - Debug ]----------"
	@cd "Bp3_proje1" && "$(MAKE)" -f  "Bp3_proje1.mk"
clean:
	@echo "----------Cleaning project:[ Bp3_proje1 - Debug ]----------"
	@cd "Bp3_proje1" && "$(MAKE)" -f  "Bp3_proje1.mk" clean
